apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster-kafka-exporter
  namespace: kafka
  labels:
    app.kubernetes.io/name: kafka-exporter
    strimzi.io/cluster: kafka-cluster
spec:
  selector:
    app.kubernetes.io/name: kafka-exporter
    strimzi.io/cluster: kafka-cluster
  ports:
    - name: metrics
      port: 9404
      targetPort: 9404
