apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames: [kafka]
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-exporter
      strimzi.io/cluster: kafka-cluster
  endpoints:
    - port: metrics
      interval: 30s
