apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-jmx
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames: [kafka]
  selector:
    matchLabels:
      strimzi.io/kind: Kafka
  podMetricsEndpoints:
    - port: tcp-prometheus
      interval: 30s
      relabelings:
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: kubernetes_pod_name
        - sourceLabels: [__meta_kubernetes_pod_label_strimzi_io_cluster]
          targetLabel: strimzi_io_cluster
        - sourceLabels: [__meta_kubernetes_pod_label_strimzi_io_name]
          targetLabel: strimzi_io_name
        - sourceLabels: [__meta_kubernetes_pod_label_strimzi_io_pool_name]
          targetLabel: pool
