apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: "4.2.0"
    metadataVersion: "4.2-IV1"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport # LoadBalancer から NodePort に変更（共有NLBを使用するため）
        tls: true
        configuration:
          bootstrap:
            nodePort: 30094
          brokers:
            - broker: 0
              advertisedHost: <KAFKA_ADVERTISED_HOST>
              nodePort: 30095
              advertisedPort: 9095
            - broker: 1
              advertisedHost: <KAFKA_ADVERTISED_HOST>
              nodePort: 30096
              advertisedPort: 9096
            - broker: 2
              advertisedHost: <KAFKA_ADVERTISED_HOST>
              nodePort: 30097
              advertisedPort: 9097
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    rack:
      topologyKey: topology.kubernetes.io/zone
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
    template:
      pod:
        tolerations:
          - key: "DedicatedKafka"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
  cruiseControl:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: cruise-control-config.yml
    template:
      pod:
        tolerations:
          - key: "DedicatedKafka"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
  entityOperator:
    topicOperator: {}
    userOperator: {}
    template:
      pod:
        tolerations:
          - key: "DedicatedKafka"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
