apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: kafka
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: <BROKER_REPLICAS>
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        class: gp3
        kraftMetadata: shared
        deleteClaim: <DELETE_CLAIM>
  resources:
    requests:
      memory: 2Gi
      cpu: "250m"
    limits:
      memory: 4Gi
      cpu: "500m"
  jvmOptions:
    -Xms: "1024m"
    -Xmx: "2048m"
  template:
    pod:
      tolerations:
        - key: "DedicatedKafka"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - kafka
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: strimzi.io/pool-name
                    operator: In
                    values:
                      - kafka
              topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              strimzi.io/name: kafka-cluster-kafka
