apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: <BINDING_NAME>
  namespace: kafka
spec:
  serviceRef:
    name: <SERVICE_NAME>
    port: <SERVICE_PORT>
  targetGroupARN: <TARGET_GROUP_ARN>
  targetType: instance
