# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event.proto
# Protobuf Python Version: 6.33.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    6,
    '',
    'event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\x12\rekscdk.kafka2\"&\n\x06\x43ommon\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x64\x61tetime\x18\x02 \x01(\t\"(\n\x04User\x12\x0e\n\x06userid\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\"?\n\x07\x43ontent\x12\x34\n\x0ehistoryrecords\x18\x01 \x03(\x0b\x32\x1c.ekscdk.kafka2.HistoryRecord\"Z\n\rHistoryRecord\x12\x11\n\thistoryid\x18\x01 \x01(\x03\x12\x10\n\x08\x64\x61tetime\x18\x02 \x01(\t\x12\x0c\n\x04memo\x18\x03 \x01(\t\x12\x16\n\x0e\x63lassification\x18\x04 \x01(\t\"}\n\x08\x45nvelope\x12%\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x15.ekscdk.kafka2.Common\x12!\n\x04user\x18\x02 \x01(\x0b\x32\x13.ekscdk.kafka2.User\x12\'\n\x07\x63ontent\x18\x03 \x01(\x0b\x32\x16.ekscdk.kafka2.Contentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMON']._serialized_start=30
  _globals['_COMMON']._serialized_end=68
  _globals['_USER']._serialized_start=70
  _globals['_USER']._serialized_end=110
  _globals['_CONTENT']._serialized_start=112
  _globals['_CONTENT']._serialized_end=175
  _globals['_HISTORYRECORD']._serialized_start=177
  _globals['_HISTORYRECORD']._serialized_end=267
  _globals['_ENVELOPE']._serialized_start=269
  _globals['_ENVELOPE']._serialized_end=394
# @@protoc_insertion_point(module_scope)
